application: trypup
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: public/css

- url: /img
  static_dir: public/img

- url: /js
  static_dir: public/js

- url: /.*
  script: _go_app